App.Book = DS.Model.extend({
  url: DS.attr("string"),
  dateCreated: DS.attr("date"),
  lastEdited: DS.attr("date"),
  createdBy: DS.attr("string"),
  location: DS.attr("string"),
  release: DS.attr("string"),
  sourceISO: DS.attr("string"),
  sourceName: DS.attr("string"),
  targetISO: DS.attr("string"),
  targetName: DS.attr("string"),
  phrases: DS.hasMany("phrase", {async: true}),
  title: DS.attr("string"),
  favorite: DS.attr("boolean"),
  banner: DS.attr("boolean"),
  bannerUrl: DS.attr("string"),
  sounds: DS.attr("boolean"),
  videos: DS.attr("boolean"),
  editing: DS.attr("boolean"),
  comments: DS.attr("boolean"),
  phraseCount: DS.attr("number"),
  views: DS.attr("number"),
  saves: DS.attr("number"),
  shares: DS.attr("number"),
  embeds: DS.attr("number")
});